name: Debug Secrets

on:
  push:
    branches:
      - main

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print secret lengths
        run: |
          echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
          echo "PORTAINER_URL length: ${#PORTAINER_URL}"
          echo "PORTAINER_USERNAME length: ${#PORTAINER_USERNAME}"
          echo "PORTAINER_PASSWORD length: ${#PORTAINER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
          PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}

          # asdadsdsa