name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Deploy to Portainer
        env:
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
          PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
        run: |
          JWT=$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "'$PORTAINER_USERNAME'", "password": "'$PORTAINER_PASSWORD'"}' $PORTAINER_URL/api/auth | jq -r .jwt)
          curl -X POST "$PORTAINER_URL/api/endpoints/1/docker/images/create?fromImage=${{ secrets.DOCKER_USERNAME }}/your-image-name&tag=latest" -H "Authorization: Bearer $JWT"
          curl -X POST "$PORTAINER_URL/api/endpoints/1/docker/containers/create" -H "Authorization: Bearer $JWT" -d '{
            "Image": "'${{ secrets.DOCKER_USERNAME }}/your-image-name:latest'",
            "name": "your-go-app",
            "HostConfig":
