name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/storagesystem:latest

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Portainer Endpoint ID
        env:
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
          PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
        run: |
          JWT=$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "'$PORTAINER_USERNAME'", "password": "'$PORTAINER_PASSWORD'"}' $PORTAINER_URL/api/auth | jq -r .jwt)
          echo "JWT: $JWT"
          ENDPOINTS=$(curl -s -X GET -H "Authorization: Bearer $JWT" -H "Content-Type: application/json" $PORTAINER_URL/api/endpoints)
          echo "Endpoints: $ENDPOINTS"
          ENDPOINT_ID=$(echo $ENDPOINTS | jq -r '.[0].Id') # Assuming the first endpoint is the desired one
          echo "Endpoint ID: $ENDPOINT_ID"
          echo "ENDPOINT_ID=$ENDPOINT_ID" >> $GITHUB_ENV

      - name: Deploy to Portainer
        env:
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
          PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
          ENDPOINT_ID: ${{ env.ENDPOINT_ID }}
        run: |
          JWT=$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "'$PORTAINER_USERNAME'", "password": "'$PORTAINER_PASSWORD'"}' $PORTAINER_URL/api/auth | jq -r .jwt)
          echo "JWT: $JWT"
          curl -X POST "$PORTAINER_URL/api/endpoints/$ENDPOINT_ID/docker/images/create?fromImage=${{ secrets.DOCKER_USERNAME }}/storagesystem&tag=latest" -H "Authorization: Bearer $JWT" -H "Content-Type: application/json"
          CONTAINER=$(curl -s -X POST "$PORTAINER_URL/api/endpoints/$ENDPOINT_ID/docker/containers/create" -H "Authorization: Bearer $JWT" -H "Content-Type: application/json" -d '{
            "Image": "'${{ secrets.DOCKER_USERNAME }}/storagesystem:latest'",
            "name": "storagesystem",
            "HostConfig": {
              "PortBindings": {
                "8000/tcp": [{"HostPort": "8080"}]
              }
            },
            "ExposedPorts": {
              "8000/ttcp": {}
            }
          }')
          echo "Container Create Response: $CONTAINER"
          CONTAINER_ID=$(echo $CONTAINER | jq -r '.Id')
          echo "Container ID: $CONTAINER_ID"
          curl -X POST "$PORTAINER_URL/api/endpoints/$ENDPOINT_ID/docker/containers/$CONTAINER_ID/start" -H "Authorization: Bearer $JWT" -H "Content-Type: application/json"
